### ISSUE TITLE
Anisotropic remeshing load imbalance with the distributed interface

### ISSUE THREAD

**Issue by prj-** [MmgTools/ParMmg#10]
In this FreeFEM [example](https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/laplace-adapt-dist-3d-PETSc.edp), we successively refine a mesh using ParMmg distributed interface. I've noticed that the output mesh is far from being properly load balanced in terms of local number of elements. See the table below for some results on 4 ranks, 4 successive calls to ParMmg (the initial decomposition is generated by METIS).
| Rank | Iteration 0 | Iteration 1 | Iteration 2 | Iteration 3 | Iteration 4 |
| ----- |:----------:|:----------:|:----------:|:----------:|-----------:|
| 0       | 2301 | 7848 | 15412 | 35777 | 91092 |
| 1        | 2254 | 1548 | 2926 | 5483 | 11078 |
| 2       | 2223 | 7199 | 12946 | 26360 | 59205 |
| 3       | 2294 | 1915 | 3768 | 6071 | 13260 |

Any idea on how to mitigate this issue? Is it the caller responsibility to load balance the mesh after a call to ParMmg, e.g., with ParMETIS or PT-SCOTCH?

**Comment by lcirrottola** [comment]
Hello,
At the moment the repartitioning algorithm is expected to trade a bit of balancing for better adaptation, and the problem is particularly visible on small meshes.
We didn't provide a final balancing step until now because we only deal with element-based partitions, and users with more complicate mesh data structures could be interested in different balancing strategies.
Anyway, it is becoming a requested feature and it is in our todolist to provide it.

**Comment by prj-** [comment]
Thanks for merging #12. Here are the new numbers.
| Rank | Iteration 0 | Iteration 1 | Iteration 2 | Iteration 3 | Iteration 4 | Iteration 6 |
| ----- |:----------:|:----------:|:----------:|:----------:|:----------:|-----------:|
| 0       | 2301 | 4662 | 8319 | 12434 | 21393 | 38978 |
| 1        | 2254 | 4648 | 8658 | 13541 | 23454 | 42600 |
| 2       | 2223 | 4574 | 7874 | 14017 | 28840 | 62082 |
| 3       | 2294 | 4626 | 7816 | 12869 | 23714 | 46744 |

Just one small remark, I now have a good amount of warnings at almost _each_ iteration.
```
### Error: Cannot merge main subgroup on proc 3

  ## Split group problem.

  ## Split group problem.

  ## Split group problem.

  ## Split group problem.

  ## Problem when splitting into a higher number of groups.

  ## Problem when splitting into a higher number of groups.

  ## Problem when splitting into a higher number of groups.

  ## Problem when splitting into a higher number of groups.

  ## Load balancing problem. Try to save the mesh and exit program.
```

**Comment by Algiane** [comment]
Hello,

Finnally I bring a slight modif to  [#12](https://github.com/MmgTools/ParMmg/pull/12): I replace the strncpy by a memcpy (faster). But thank you for pointing out the issue.

Luca is currently adding the final load balancing.

For your last remark: ParMmg " Errors " are important, here it seems that we are not able the merge two sub-meshes. Maybe it is a memory issue, I will look at this.

Is it urgent or can it be treated in a few weeks?

Thank you by advance,
Algiane

**Comment by prj-** [comment]
I'm in no rush, don't worry, and thanks for the continuous improvements. Feel free to close the issue after (or before, it's not big deal) you fix the warnings/errors.

**Comment by prj-** [comment]
I'm now getting much better results, so I'll close this issue, thanks! Here is an updated table just FYI.
| Rank | Iteration 0 | Iteration 1 | Iteration 2 | Iteration 3 | Iteration 4 | Iteration 5 | Iteration 6 | Iteration 7 |
| ----- |:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
| 0       | 2301 | 4554 | 9487 | 19599 | 53100 | 143290 | 354732 | 1022758 | 2740057 |
| 1        | 2254 | 4597 | 9536 | 19788 | 54082 | 148955 | 374039 | 1037891 | 2808392 |
| 2       | 2223 | 4506 | 8508 | 22392 | 48744 | 132821 | 379706 | 960440 | 2688960 |
| 3       | 2294 | 4648 | 8228 | 19126 | 53766 | 139752 | 379943 | 1076794 | 2782321 |

![corner](https://user-images.githubusercontent.com/5539428/80095263-eba7f480-8567-11ea-99e0-8f9cac215d78.png)
