### ISSUE TITLE
Optim doesn't improve boundary tets

### ISSUE THREAD

**Issue by krober10nd** [MmgTools/ParMmg#3]
Hello,

I'm using parmmg to improve the quality of an existing 3d tet mesh. However, poor quality elements on the boundary are not improved, while the interior elements are heavily improved. Is there an option preventing the optimization of the boundary elements?

Thanks!

**Comment by lcirrott** [comment]
Hello,
Boundary adaptation is not supported in the current release, so yes, the mmg option -nosurf is applied by default.
Boundary adaptation is already in our to-do list for the next releases.
Cheers,
Luca
