### ISSUE TITLE
local/global id for interface faces for face API mode

### ISSUE THREAD

**Issue by prudhomm** [MmgTools/ParMmg#30]
it seems that the global id for interface faces is needed. 
We never compute/use them, we know however for a given face its id in the current proc as well as in the remote proc.

When we use `PMMG_Set_triangle` should the id be local or global in distributed mode ?

Should the id of `PMMG_Set_triangle` correspond to the local or global id of the arrays passed to `PMMG_Set_ithNodeCommunicator_faces` when the face is at the interface between processes ?

thanks in advance

**Comment by prj-** [comment]
`PMMG_Set_triangle` ID should be local.

**Comment by prudhomm** [comment]
@prj- thanks, how about `PMMG_Set_ithNodeCommunicator_faces` ?
Also should the global ids be contiguous ? or they can be arbitrary ? if the latter, I will implement the global id using a hash function

**Comment by prudhomm** [comment]
one more question: `PMMG_Set_meshSize` get global number of vertices, tets ... or local only  ? I would think local

**Comment by prj-** [comment]
For `PMMG_Set_meshSize`, you are thinking correctly ;)
The IDs do not need to be contiguous.

**Comment by prudhomm** [comment]
thank you @prj- 
hopefully I will have parmmg running now  in feelpp thanks to you and parmmg team!

**Comment by lcirrottola** [comment]
Hello!
As long as the value of the global ID is unique, it is fine! (So the Cantor pairing works great as long as the value be represented by an `int`)
Addendum: The global ID on faces is only used to match the faces on the two sides of the communicator, if they are not passed in the same order on the two sides (i.e. if `isNotOrdered`is 1).
If you can set the faces in the same order on the two sides of the communicator (and set `isNotOrdered` to 0), then the values of the global IDs are ignored.

**Comment by prudhomm** [comment]
@lcirrottola our faces are now ordered and I set `isNotOrdered` to 0. However, there is still a matching issue: I  check on my  side the face id on both sides and the vertices, they are the same. 
Parmmg complains that it does not match: I get something like:
```
# Warning: MMG5_chkBdryTria: 28 extra boundaries provided. Ignored
  ## Error1: PMMG_check_extFaceComm: item 0 of the external communicator 1->0:
                     vertex 0: 1.000000e+00 5.000000e-01 0.000000e+00 -- 1.000000e+00 5.000000e-01 1.000000e+00 (dist = 1.000000e+00)
  ## Error2: PMMG_check_extFaceComm: item 0 of the external communicator 1->0:
                     vertex 0: 6.479167e-01 6.437500e-01 0.000000e+00 -- 1.000000e+00 5.000000e-01 0.000000e+00 (dist = 1.446267e-01)
  ## Error1: PMMG_check_extFaceComm: item 1 of the external communicator 1->0:
                     vertex 1: 1.000000e+00 5.000000e-01 1.000000e+00 -- 3.750000e-01 3.750000e-01 1.000000e+00 (dist = 4.062500e-01)
  ## Error2: PMMG_check_extFaceComm: item 1 of the external communicator 1->0:
                     vertex 1: 1.000000e+00 5.000000e-01 0.000000e+00 -- 3.750000e-01 3.750000e-01 0.000000e+00 (dist = 4.062500e-01)
  ## Error3: PMMG_check_extFaceComm: item 1 of the external communicator 1->0:
                     vertex 1: 6.479167e-01 6.437500e-01 1.000000e+00 -- 0.000000e+00 5.000000e-01 0.000000e+00 (dist = 1.440460e+00)
  ## Error1: PMMG_check_extFaceComm: item 0 of the external communicator 0->1:
                     vertex 0: 1.000000e+00 5.000000e-01 1.000000e+00 -- 1.000000e+00 5.000000e-01 0.000000e+00 (dist = 1.000000e+00)
  ## Error3: PMMG_check_extFaceComm: item 0 of the external communicator 0->1:
                     vertex 0: 1.000000e+00 5.000000e-01 0.000000e+00 -- 6.479167e-01 6.437500e-01 0.000000e+00 (dist = 1.446267e-01)
  ## Error1: PMMG_check_extFaceComm: item 1 of the external communicator 0->1:
                     vertex 1: 3.750000e-01 3.750000e-01 1.000000e+00 -- 1.000000e+00 5.000000e-01 1.000000e+00 (dist = 4.062500e-01)
  ## Error2: PMMG_check_extFaceComm: item 1 of the external communicator 0->1:
                     vertex 1: 0.000000e+00 5.000000e-01 0.000000e+00 -- 6.479167e-01 6.437500e-01 1.000000e+00 (dist = 1.440460e+00)
  ## Error3: PMMG_check_extFaceComm: item 1 of the external communicator 0->1:
                     vertex 1: 3.750000e-01 3.750000e-01 0.000000e+00 -- 1.000000e+00 5.000000e-01 0.000000e+00 (dist = 4.062500e-01)
feelpp_test_remesh: /home/prudhomm/Devel/feelpp.release/feelpp/contrib/parmmg/src/communicators_pmmg.c:1200: int PMMG_build_nodeCommFromFaces(PMMG_pParMesh): Assertion `PMMG_check_extFaceComm ( parmesh )' failed.
feelpp_test_remesh: /home/prudhomm/Devel/feelpp.release/feelpp/contrib/parmmg/src/communicators_pmmg.c:1200: int PMMG_build_nodeCommFromFaces(PMMG_pParMesh): Assertion `PMMG_check_extFaceComm ( parmesh )' failed.
```

The vertices do not correspond and they actually do not belong to the same face, for example these two faces should match but they don't (they correspond to the first comm face in the list)

```
GeoND object of shape 64
 Number of Vertices = 3
   Number of Points = 3
                 id = 39
                  G = [3,3]((1,0.647917,0.647917),(0.5,0.64375,0.64375),(0,0,1))
POINT id = 0
----- BEGIN of Geo0D ---
id = 9 node:[3](1.000000e+00,5.000000e-01,0.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
POINT id = 1
----- BEGIN of Geo0D ---
id = 19 node:[3](6.479167e-01,6.437500e-01,0.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
POINT id = 2
----- BEGIN of Geo0D ---
id = 23 node:[3](6.479167e-01,6.437500e-01,1.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
----- END OF GeoND data ---
```

```
GeoND object of shape 64
 Number of Vertices = 3
   Number of Points = 3
                 id = 64
                  G = [3,3]((1,0.647917,0.647917),(0.5,0.64375,0.64375),(0,0,1))
POINT id = 0
----- BEGIN of Geo0D ---
id = 9 node:[3](1.000000e+00,5.000000e-01,0.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
POINT id = 1
----- BEGIN of Geo0D ---
id = 19 node:[3](6.479167e-01,6.437500e-01,0.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
POINT id = 2
----- BEGIN of Geo0D ---
id = 23 node:[3](6.479167e-01,6.437500e-01,1.000000e+00)
is a vertex = 0
----- END OF Geo0D ---
----- END OF GeoND data ---
```

here is the list of sorted faces on both side between proc 0 and 1
```
(39, 64) (41, 63) (61, 71) (63, 52) (67, 49) (69, 46)
```
the first of each pair correspond to the lowest process rank and the second to the higher one. The exact same array is generated on both side.

I am certainly missing something but I currently don't see it

**Comment by prudhomm** [comment]
also I see this in `chkcomm_pmmg.c`

```
 /* Travel the face in opposite direction for the two communicators */
      x   = doublevalues[9*idx  ] - rtorecv[9*i  ];
      y   = doublevalues[9*idx+1] - rtorecv[9*i+1];
      z   = doublevalues[9*idx+2] - rtorecv[9*i+2];
      if ( x*x + y*y + z*z > MMG5_EPSOK ) {
        printf("  ## Error1: %s: item %d of the external communicator %d->%d:\n"
               "                     vertex %d: %e %e %e -- %e %e %e"
               " (dist = %e)\n",__func__,i,
               parmesh->myrank,color,idx,doublevalues[9*idx],doublevalues[9*idx+1],
               doublevalues[9*idx+2],rtorecv[9*i],rtorecv[9*i+1],rtorecv[9*i+2],
               x*x + y*y + z*z);
        ier = 0;
      }

      x   = doublevalues[9*idx+3  ] - rtorecv[9*i+6  ];
      y   = doublevalues[9*idx+3+1] - rtorecv[9*i+6+1];
      z   = doublevalues[9*idx+3+2] - rtorecv[9*i+6+2];
      if ( x*x + y*y + z*z > MMG5_EPSOK ) {
        printf("  ## Error2: %s: item %d of the external communicator %d->%d:\n"
               "                     vertex %d: %e %e %e -- %e %e %e"
               " (dist = %e)\n",__func__,i,
               parmesh->myrank,color,idx,doublevalues[9*idx+3],doublevalues[9*idx+4],
               doublevalues[9*idx+5],rtorecv[9*i+6],rtorecv[9*i+7],rtorecv[9*i+8],
               x*x + y*y + z*z);
        ier = 0;
      }

      x   = doublevalues[9*idx+6  ] - rtorecv[9*i+3  ];
      y   = doublevalues[9*idx+6+1] - rtorecv[9*i+3+1];
      z   = doublevalues[9*idx+6+2] - rtorecv[9*i+3+2];
      if ( x*x + y*y + z*z > MMG5_EPSOK ) {
        printf("  ## Error3: %s: item %d of the external communicator %d->%d:\n"
               "                     vertex %d: %e %e %e -- %e %e %e"
               " (dist = %e)\n",__func__,i,
               parmesh->myrank,color,idx,doublevalues[9*idx+6],doublevalues[9*idx+7],
               doublevalues[9*idx+8],rtorecv[9*i+3],rtorecv[9*i+4],rtorecv[9*i+5],
               x*x + y*y + z*z);
        ier = 0;
      }
```

why aren't the faces traversed in the same order ?

**Comment by prudhomm** [comment]
@lcirrottola only a subset of faces are wrong. 
I am currently checking where the data went wrong

**Comment by lcirrottola** [comment]
Hello @prudhomm,
to help you debug:

- in `chkcomm_pmmg.c`the faces are processed in opposite order because boundary and parallel triangles on each process are oriented to give an outward normal vector (so, when performing the check, the pair face collected from the other side of the communicator has inward normal on the receiving proc);

- internally, parmmg converts the triangle index given in the API to a triplet made by the tetrahedron index (local on the process), the index of the face (local on the tetrahedron), and the index of a choosen node (local on the tetrahedron). The purpose is to allow to loop on the vertices of the triangle in the same order on the two processes, starting from this same choosen node. For the face communicator, the node with the highest coordinates is choosen. This is done in: https://github.com/MmgTools/ParMmg/blob/5ffc6ada4afb1af50a43e1fa6f4c409cff2ea25c/src/communicators_pmmg.c#L823

I will check that everything is ok in this step...

**Comment by lcirrottola** [comment]
Just to be sure that I get it:

> here is the list of sorted faces on both side between proc 0 and 1
>
>>(39, 64) (41, 63) (61, 71) (63, 52) (67, 49) (69, 46)
>
>the first of each pair correspond to the lowest process rank and the second to the higher one. The exact same array is generated on both side.

These indices are local on the processes, right? (I tried to visualize it here https://github.com/MmgTools/ParMmg/wiki/Manually-distributed-library-example but it should not add much to the discussion).

Just from the log, I don't get where the triangle (3.750000e-01 3.750000e-01 1.000000e+00)--(3.750000e-01 3.750000e-01 0.000000e+00)--(0.000000e+00 5.000000e-01 0.000000e+00) comes from, nor the point (1.000000e+00 5.000000e-01 1.000000e+00)...
Do not hesitate to share a mesh or a code snippet if you need  more help.

**Comment by prudhomm** [comment]
@lcirrottola I managed to find the problem. I changed the way I traverse the faces (through the elements on both sides of the face) and now I get the proper data. The (subtle)issue was on our side.  Thank you very much for the explanation! I had to go deeper in parmmg and understand better the data structure to find the issue.

**Comment by prudhomm** [comment]
@lcirrottola see #33 for some screenshots. 
Now I have to reconstruct the ghost data properly and there is still a problem there ;)

**Comment by lcirrottola** [comment]
Glad it is progressing!
