### ISSUE TITLE
ghost data

### ISSUE THREAD

**Issue by prudhomm** [MmgTools/ParMmg#33]
In a finite element code,  we often use ghost mesh data. Gmsh provides this information.
After an adaptation we lose this information.
Would it be possible to provide it? 
Since the interface is fixed, we know the element from the other side (we have the information in the initial mesh)
but the coordinates of the 4-th vertex(not on the  interface) may have been moved.
is that correct ?

/cc @Algiane @lcirrottola

**Comment by prj-** [comment]
If you are referring to the interface among subdomain processes, then they are not frozen. What is _currently_ (but hopefully not in the future anymore) frozen is the surface of the global mesh.

**Comment by prudhomm** [comment]
ok I thought the interface between subdomain was frozen. @prj- do you reinterpolate yourself the scalar and vector fields or you let parmmg do it for you ?

**Comment by prudhomm** [comment]
do you rebuild the ghost data as well @prj- ?

**Comment by prj-** [comment]
Yes, I re-interpolate myself, and yes, I rebuild the ghost data as well.

**Comment by prudhomm** [comment]
I get this kind of partitioning by parmmg (note the element alone). do you get this kind of results as well ?

![Screenshot 2021-01-21 at 16 10 35](https://user-images.githubusercontent.com/151693/105369815-347a0000-5c03-11eb-8b9a-a3671c58e961.png)

**Comment by prj-** [comment]
It looks like your mesh is tiny. I usually don't get great results with ParMmg on tiny meshes and switch to plain Mmg which is more robust in this case. Do you still get disconnected domains with a lower `Mesh.CharacteristicLengthFromPoints`? (not ideal for debugging, I do agree :\\)

**Comment by prudhomm** [comment]
it is better on a finer mesh

![Screenshot 2021-01-21 at 16 20 09](https://user-images.githubusercontent.com/151693/105371758-35ac2c80-5c05-11eb-85e6-63b6e78661e7.png)

**Comment by prj-** [comment]
LGTM :)

**Comment by prudhomm** [comment]
with a different metric

2 procs

![Screenshot 2021-01-21 at 16 32 22](https://user-images.githubusercontent.com/151693/105372779-3f825f80-5c06-11eb-977d-47ebc37ebfa7.png)

works nicely up to the 28 cores on my machine.
took me some time to find an issue with the faces we are passing to parmmg

**Comment by lcirrottola** [comment]
> In a finite element code, we often use ghost mesh data. Gmsh provides this information.
> After an adaptation we lose this information.
> Would it be possible to provide it?
> Since the interface is fixed, we know the element from the other side (we have the information in the initial mesh)
> but the coordinates of the 4-th vertex(not on the interface) may have been moved.
> is that correct ?
> 
> /cc @Algiane @lcirrottola

Hello @prudhomm, no at the moment ghost entities are not supported, because we would need to reconstruct the ghost layer after mesh adaptation and that would be quite solver-dependent.

**Comment by lcirrottola** [comment]
> If you are referring to the interface among subdomain processes, then they are not frozen. What is _currently_ (but hopefully not in the future anymore) frozen is the surface of the global mesh.

Ehm... The interface _is_ frozen. But the interface you set is not the interface you get, because:

1. multiple remeshing+interface displacement (repartitioning) iterations are performed to adapt everywhere,
2. the partition you give can be further split in several groups of elements by tuning the `-mesh-size` parameter (so a second level of partitioning is added and temporarily adds new interfaces).

So for now the boundary _and_ the interface (at the given iteration) are frozen. Actually adaptation on smooth boundaries can be activated but only for beta tests, adaptation on non-smooth boundaries require still some coding and is being delayed by higher-priority duties...

**Comment by lcirrottola** [comment]
> I get this kind of partitioning by parmmg (note the element alone). do you get this kind of results as well ?
> 
> ![Screenshot 2021-01-21 at 16 10 35](https://user-images.githubusercontent.com/151693/105369815-347a0000-5c03-11eb-8b9a-a3671c58e961.png)

Output partitions are load-balanced by default, and we have noticed that on small meshes with few processes the Metis K-way partitioning can give results like this (so on less than 8 processes we switch to the Metis recursive algorithm, but with very few elements we have still seen problems).

**Comment by prudhomm** [comment]
@lcirrottola

**Comment by prudhomm** [comment]
| Ehm... The interface is frozen. But the interface you set is not the interface you get, because:

@lcirrottola ok I understood this initially but not completely. Just to make sure I understand now : the faces at the interface are **required** in one iteration and so will still be there in the final mesh of the iteration however the mesh is repartitionned using (par) metis and so these faces may not be at an interface anymore. To adapt everywhere multiple iterations are then necessary.
Is that correct?

**Comment by prj-** [comment]
ParMmg works iteratively: once the first iteration is done, with frozen interfaces, the mesh is repartitioned, so that all elements, even those close to the original interfaces, get "adapted". Throughout this iterative process, new sets of interfaces are generated. So if you set the maximum number of ParMmg iterations `PMMG_IPARAM_niter` to 1 (default value is 3), then indeed you can say that your interfaces are frozen.

**Comment by lcirrottola** [comment]
@prudhomm @prj- yes exactly, at each iteration interfaces are frozen (required) during adaptation, and are "switched" with the repartitioning performed immediately after.
